import { CaseCard } from "../types";

export const CASE_DECK: CaseCard[] = [
  // --- 10 BASIC CASES (2 PTS) ---
  {
    id: "C-B01",
    type: "CASE",
    difficulty: "BASIC",
    points: 2,
    titleTh: "Bone Scan ประเมินกระดูกทั่วตัว",
    titleEn: "Whole Body Bone Scintigraphy",
    promptTh: "การตรวจสแกนกระดูก (Bone Scan) เพื่อประเมินภาวะกระดูกทั่วร่างกาย",
    organHint: "bone",
    clueId: "T-09",
    acceptedRpIds: ["R-05", "R-06", "R-11"],
    acceptedMechIds: ["M-06", "M-11"],
    explanationTh: "การตรวจ Bone Scan นิยมใช้ ⁹⁹ᵐTc-MDP หรือ ¹⁸F-NaF โดยสารจะสร้างพันธะกับผลึกไฮดรอกซีอะพาไทต์ผ่านกลไก Chemisorption หรือ Ion Exchange",
    body: ["โจทย์ระดับพื้นฐาน: ตรวจกระดูกทั่วตัว"],
    illustration: "bone",
    tags: ["bone", "basic"]
  },
  {
    id: "C-B02",
    type: "CASE",
    difficulty: "BASIC",
    points: 2,
    titleTh: "Thyroid Imaging ต่อมไทรอยด์",
    titleEn: "Thyroid Scintigraphy",
    promptTh: "การตรวจสแกนต่อมไทรอยด์ (Thyroid Scan) เพื่อดูการทำงานและการกระจายตัวของเนื้อเยื่อไทรอยด์",
    organHint: "thyroid",
    clueId: "T-03",
    acceptedRpIds: ["R-02", "R-03"],
    acceptedMechIds: ["M-01"],
    explanationTh: "ต่อมไทรอยด์ใช้กลไก Active Transport ผ่าน Na⁺/I⁻ symporter ในการดึงดูด ¹²³I หรือ ⁹⁹ᵐTcO4⁻ เข้าสู่เซลล์",
    body: ["โจทย์ระดับพื้นฐาน: ต่อมไทรอยด์"],
    illustration: "thyroid",
    tags: ["thyroid", "basic"]
  },
  {
    id: "C-B03",
    type: "CASE",
    difficulty: "BASIC",
    points: 2,
    titleTh: "Liver-Spleen Scan",
    titleEn: "Liver-Spleen Scintigraphy",
    promptTh: "การตรวจสแกนตับและม้ามเพื่อประเมินเซลล์ในระบบเรติคูโลเอนโดทีเลียล (RES)",
    organHint: "liver",
    clueId: "T-06",
    acceptedRpIds: ["R-09"],
    acceptedMechIds: ["M-04"],
    explanationTh: "อนุภาค ⁹⁹ᵐTc-sulfur colloid ถูกจับกลืนโดย Kupffer cells ในตับและ Macrophages ในม้ามด้วยกลไก Phagocytosis",
    body: ["โจทย์ระดับพื้นฐาน: ตับและม้าม"],
    illustration: "liver_spleen",
    tags: ["liver", "spleen", "basic"]
  },
  {
    id: "C-B04",
    type: "CASE",
    difficulty: "BASIC",
    points: 2,
    titleTh: "Renal Cortical Scan หา Scar",
    titleEn: "Renal Cortical Scintigraphy",
    promptTh: "การตรวจภาพเนื้อเยื่อไตส่วนนอก (Cortex) เพื่อหารอยแผลเป็นหรือการอักเสบกรวยไต",
    organHint: "kidney",
    clueId: "T-02",
    acceptedRpIds: ["R-12"],
    acceptedMechIds: ["M-06", "M-01"],
    explanationTh: "⁹⁹ᵐTc-DMSA จะจับติดแน่นกับเซลล์ท่อไตส่วนต้น (Proximal tubules) ในเนื้อเยื่อคอร์เทกซ์ของไต",
    body: ["โจทย์ระดับพื้นฐาน: เนื้อไต"],
    illustration: "kidney",
    tags: ["kidney", "dmsa", "basic"]
  },
  {
    id: "C-B05",
    type: "CASE",
    difficulty: "BASIC",
    points: 2,
    titleTh: "Myocardial Perfusion Scan (MPI)",
    titleEn: "Myocardial Perfusion Imaging",
    promptTh: "การตรวจประเมินการไหลเวียนเลือดของกล้ามเนื้อหัวใจเพื่อหาภาวะกล้ามเนื้อหัวใจขาดเลือด",
    organHint: "heart",
    clueId: "T-04",
    acceptedRpIds: ["R-17", "R-18"],
    acceptedMechIds: ["M-05", "M-01"],
    explanationTh: "⁹⁹ᵐTc-sestamibi แพร่ผ่านเยื่อหุ้มเซลล์ (Passive diffusion) จับในไมโทคอนเดรีย หรือใช้ ²⁰¹Tl ผ่าน Na⁺/K⁺ ATPase (Active Transport)",
    body: ["โจทย์ระดับพื้นฐาน: กล้ามเนื้อหัวใจ"],
    illustration: "cell",
    tags: ["heart", "mpi", "basic"]
  },
  {
    id: "C-B06",
    type: "CASE",
    difficulty: "BASIC",
    points: 2,
    titleTh: "Lung Perfusion Scan",
    titleEn: "Pulmonary Perfusion Scintigraphy",
    promptTh: "การตรวจประเมินการไหลเวียนเลือดในหลอดเลือดฝอยปอดโดยตรง",
    organHint: "lung",
    clueId: "T-01",
    acceptedRpIds: ["R-07"],
    acceptedMechIds: ["M-03"],
    explanationTh: "ใช้อนุภาค ⁹⁹ᵐTc-MAA ขนาด 10–50 μm เพื่อให้เกิดการอุดกั้นชั่วคราวในหลอดเลือดฝอยปอดด้วยกลไก Capillary Blockade",
    body: ["โจทย์ระดับพื้นฐาน: ปอด"],
    illustration: "lung",
    tags: ["lung", "maa", "basic"]
  },
  {
    id: "C-B07",
    type: "CASE",
    difficulty: "BASIC",
    points: 2,
    titleTh: "Hepatobiliary Scan (HIDA)",
    titleEn: "Biliary System Scintigraphy",
    promptTh: "การตรวจระบบท่อน้ำดีและถุงน้ำดี (HIDA Scan) เพื่อดูการทำงานของตับและการขับน้ำดี",
    organHint: "liver",
    clueId: "T-07",
    acceptedRpIds: ["R-10"],
    acceptedMechIds: ["M-01", "M-12"],
    explanationTh: "⁹⁹ᵐTc-mebrofenin ถูกดึงดูดเข้าสู่เซลล์ตับผ่านระบบ Active transport แล้วขับออกสู่ระบบท่อน้ำดี",
    body: ["โจทย์ระดับพื้นฐาน: ทางเดินน้ำดี"],
    illustration: "liver_spleen",
    tags: ["hida", "liver", "basic"]
  },
  {
    id: "C-B08",
    type: "CASE",
    difficulty: "BASIC",
    points: 2,
    titleTh: "Brain Perfusion SPECT",
    titleEn: "Cerebral Blood Flow Scintigraphy",
    promptTh: "การตรวจประเมินการไหลเวียนเลือดในสมองเพื่อดูภาวะสมองเสื่อมหรือจุดกำเนิดโรคลมชัก",
    organHint: "brain",
    clueId: "T-12",
    acceptedRpIds: ["R-19", "R-20"],
    acceptedMechIds: ["M-05"],
    explanationTh: "⁹⁹ᵐTc-HMPAO หรือ ⁹⁹ᵐTc-ECD เป็นสารละลายในไขมันที่แพร่ผ่าน Blood-Brain Barrier (Passive diffusion) แล้วถูกกักขังในเนื้อสมอง",
    body: ["โจทย์ระดับพื้นฐาน: สมอง"],
    illustration: "cell",
    tags: ["brain", "spect", "basic"]
  },
  {
    id: "C-B09",
    type: "CASE",
    difficulty: "BASIC",
    points: 2,
    titleTh: "Infection Scan ด้วยเม็ดเลือดขาว",
    titleEn: "Labeled Leukocyte Scintigraphy",
    promptTh: "การตรวจหาตำแหน่งการติดเชื้อซ่อนเร้นหรือกระดูกอักเสบโดยใช้เม็ดเลือดขาวของผู้ป่วย",
    organHint: "wbc",
    clueId: "T-17",
    acceptedRpIds: ["R-21"],
    acceptedMechIds: ["M-08"],
    explanationTh: "¹¹¹In-WBC เคลื่อนที่ไปยังตำแหน่งที่มีการอักเสบหรือติดเชื้อตามสารเคมีชักนำด้วยกลไก Cellular Migration",
    body: ["โจทย์ระดับพื้นฐาน: เม็ดเลือดขาว"],
    illustration: "migration",
    tags: ["infection", "wbc", "basic"]
  },
  {
    id: "C-B10",
    type: "CASE",
    difficulty: "BASIC",
    points: 2,
    titleTh: "NET Scan ด้วย Somatostatin Analog",
    titleEn: "Neuroendocrine Tumor Imaging",
    promptTh: "การตรวจเนื้องอกระบบประสาทและต่อมไร้ท่อด้วยสารเลียนแบบฮอร์โมนโซมาโตสแตติน",
    organHint: "tumor",
    clueId: "T-05",
    acceptedRpIds: ["R-15", "R-16"],
    acceptedMechIds: ["M-07"],
    explanationTh: "¹¹¹In-pentetreotide หรือ ⁶⁸Ga-DOTATATE มีความจำเพาะสูงในการจับกับ Somatostatin Receptor (SSTR) ด้วยกลไก Receptor Binding",
    body: ["โจทย์ระดับพื้นฐาน: ตัวรับเนื้องอก"],
    illustration: "receptor",
    tags: ["net", "tumor", "basic"]
  },

  // --- 10 CLINICAL CASES (4 PTS) ---
  {
    id: "C-05",
    type: "CASE",
    difficulty: "CLINICAL",
    points: 4,
    titleTh: "ผู้ป่วยสงสัย Pulmonary Embolism",
    titleEn: "Suspected Acute Pulmonary Embolism",
    promptTh: "ผู้ป่วยสงสัย Pulmonary Embolism ต้องการประเมินการกระจายของเลือดในปอด (Lung Perfusion Scan)",
    organHint: "lung",
    clueId: "T-01",
    acceptedRpIds: ["R-07"],
    acceptedMechIds: ["M-03"],
    explanationTh: "อนุภาค MAA ขนาด 10–50 μm ติดค้างที่หลอดเลือดฝอยปอดด้วยกลไก Capillary Blockade จึงใช้ดู perfusion เพื่อช่วยวินิจฉัย PE",
    body: ["ผู้ป่วยมีอาการหอบเหนื่อยเฉียบพลัน สงสัยลิ่มเลือดอุดกั้นในปอด"],
    illustration: "lung",
    tags: ["pe", "lung", "clinical"]
  },
  {
    id: "C-02",
    type: "CASE",
    difficulty: "CLINICAL",
    points: 4,
    titleTh: "ผู้ป่วยปวดหลัง สงสัยมะเร็งแพร่กระจายไปกระดูก",
    titleEn: "Back Pain with Suspected Bone Metastases",
    promptTh: "ผู้ป่วยมีอาการปวดหลัง และสงสัยการแพร่กระจายของมะเร็งไปยังกระดูก ควรเลือกสารและกลไกใด?",
    organHint: "bone",
    clueId: "T-14",
    acceptedRpIds: ["R-05", "R-06", "R-11"],
    acceptedMechIds: ["M-06", "M-11"],
    explanationTh: "กระดูกที่มีมะเร็งแพร่กระจายจะมีการสร้างกระดูกซ่อมแซมสูง สาร ⁹⁹ᵐTc-MDP จะจับกับผลึกด้วยกลไก Chemisorption หรือ ¹⁸F-NaF ด้วย Ion Exchange",
    body: ["ผู้ป่วยมะเร็งต่อมลูกหมาก มีอาการปวดหลังเรื้อรัง"],
    illustration: "bone",
    tags: ["bone", "metastases", "clinical"]
  },
  {
    id: "C-07",
    type: "CASE",
    difficulty: "CLINICAL",
    points: 4,
    titleTh: "ผู้ป่วยตับแข็งเรื้อรัง ประเมินการทำงานตับและม้าม",
    titleEn: "Cirrhosis with RES Colloid Shift",
    promptTh: "ผู้ป่วยมีภาวะตับแข็งเรื้อรัง ต้องการประเมินการทำงานของตับและม้าม ใช้สารและกลไกใด?",
    organHint: "liver",
    clueId: "T-13",
    acceptedRpIds: ["R-09"],
    acceptedMechIds: ["M-04"],
    explanationTh: "ใช้ ⁹⁹ᵐTc-sulfur colloid ผ่านกลไก Phagocytosis ในผู้ป่วยตับแข็งจะพบปรากฏการณ์ colloid shift ไปที่ม้ามและไขกระดูกเด่นชัด",
    body: ["ผู้ป่วย Cirrhosis มีภาวะความดันหลอดเลือดตับสูง"],
    illustration: "liver_spleen",
    tags: ["liver", "cirrhosis", "clinical"]
  },
  {
    id: "C-11",
    type: "CASE",
    difficulty: "CLINICAL",
    points: 4,
    titleTh: "ผู้ป่วยเนื้องอกระบบประสาท (NET)",
    titleEn: "Neuroendocrine Tumor Localization",
    promptTh: "ผู้ป่วยมีเนื้องอกระบบประสาท (neuroendocrine tumor) ต้องการตรวจวินิจฉัย ใช้สารและกลไกใด?",
    organHint: "tumor",
    clueId: "T-16",
    acceptedRpIds: ["R-15", "R-16"],
    acceptedMechIds: ["M-07"],
    explanationTh: "เซลล์ NET แสดงตัวรับ SSTR จำนวนมาก จึงใช้ ¹¹¹In-pentetreotide หรือ ⁶⁸Ga-DOTATATE ผ่านกลไก Receptor Binding",
    body: ["ผู้ป่วยมีอาการหน้าแดง ท้องเสีย ถ่ายภาพหาตำแหน่งก้อน Carcinoid"],
    illustration: "receptor",
    tags: ["net", "tumor", "clinical"]
  },
  {
    id: "C-C05",
    type: "CASE",
    difficulty: "CLINICAL",
    points: 4,
    titleTh: "ถ่ายอุจจาระเป็นเลือด สงสัย GI Bleeding",
    titleEn: "Active Lower Gastrointestinal Bleeding",
    promptTh: "ถ่ายอุจจาระเป็นเลือดสด สงสัยภาวะเลือดออกในทางเดินอาหารส่วนล่าง ต้องการหาตำแหน่งเลือดออก",
    organHint: "blood_pool",
    clueId: "T-08",
    acceptedRpIds: ["R-23"],
    acceptedMechIds: ["M-10"],
    explanationTh: "ใช้ ⁹⁹ᵐTc-labeled RBC ที่กักอยู่ในระบบหลอดเลือด (Compartmental localization) เมื่อมีเลือดออก สารจะรั่วไหลและเคลื่อนที่ไปตามการบีบตัวของลำไส้",
    body: ["ผู้ป่วยมีเลือดออกไม่ทราบสาเหตุ ความดันเริ่มลด"],
    illustration: "compartment",
    tags: ["gi_bleed", "rbc", "clinical"]
  },
  {
    id: "C-C06",
    type: "CASE",
    difficulty: "CLINICAL",
    points: 4,
    titleTh: "เด็กถ่ายเป็นเลือด สงสัย Meckel's Diverticulum",
    titleEn: "Pediatric Bleeding - Meckel's Diverticulum",
    promptTh: "เด็กอายุ 4 ปี ถ่ายเป็นมูกเลือดปน สงสัย Meckel's diverticulum ที่มีเยื่อบุกระเพาะผิดที่",
    organHint: "meckel",
    clueId: "T-03",
    acceptedRpIds: ["R-03"],
    acceptedMechIds: ["M-01"],
    explanationTh: "เซลล์เยื่อบุกระเพาะที่อยู่ผิดที่ (Ectopic gastric mucosa) มีโปรตีน NIS สามารถจับ ⁹⁹ᵐTc-pertechnetate ได้ด้วย Active Transport",
    body: ["Meckel's scan ในผู้ป่วยเด็ก"],
    illustration: "thyroid",
    tags: ["meckel", "pediatric", "clinical"]
  },
  {
    id: "C-C07",
    type: "CASE",
    difficulty: "CLINICAL",
    points: 4,
    titleTh: "ฮอร์โมน PTH สูง สงสัย Parathyroid Adenoma",
    titleEn: "Primary Hyperparathyroidism",
    promptTh: "ระดับฮอร์โมน PTH และแคลเซียมในเลือดสูง สงสัยเนื้องอกต่อมพาราไทรอยด์ ต้องการหาตำแหน่งก้อน",
    organHint: "parathyroid",
    clueId: "T-19",
    acceptedRpIds: ["R-17"],
    acceptedMechIds: ["M-05", "M-01"],
    explanationTh: "⁹⁹ᵐTc-sestamibi แพร่เข้าเซลล์ (Passive diffusion) และจับติดแน่นในไมโทคอนเดรียที่หนาแน่นของเซลล์ Oxyphil ในเนื้องอกพาราไทรอยด์",
    body: ["Parathyroid Scintigraphy (Dual-phase MIBI)"],
    illustration: "cell",
    tags: ["parathyroid", "mibi", "clinical"]
  },
  {
    id: "C-C08",
    type: "CASE",
    difficulty: "CLINICAL",
    points: 4,
    titleTh: "ไข้ไม่ทราบสาเหตุ สงสัย Abscess ซ่อนเร้น",
    titleEn: "Fever of Unknown Origin (FUO)",
    promptTh: "ผู้ป่วยมีไข้สูงไม่ทราบสาเหตุเป็นเวลานาน สงสัยฝีหนองหรือการติดเชื้อซ่อนเร้นในช่องท้อง",
    organHint: "infection",
    clueId: "T-17",
    acceptedRpIds: ["R-21"],
    acceptedMechIds: ["M-08"],
    explanationTh: "¹¹¹In-labeled WBC เคลื่อนที่ไปยังตำแหน่งที่มีการรวมกลุ่มของเชื้อแบคทีเรียและฝีหนองผ่านกลไก Cellular Migration",
    body: ["ค้นหาแหล่งต้นตอของไข้และการติดเชื้อ"],
    illustration: "migration",
    tags: ["fuo", "infection", "clinical"]
  },
  {
    id: "C-C09",
    type: "CASE",
    difficulty: "CLINICAL",
    points: 4,
    titleTh: "ไตบวมน้ำ สงสัยท่อไตอุดกั้น",
    titleEn: "Hydronephrosis & Ureteral Obstruction",
    promptTh: "ผู้ป่วยมีภาวะไตบวมน้ำ (Hydronephrosis) ต้องการแยกภาวะท่อไตอุดกั้นด้วยการตรวจ Renogram",
    organHint: "kidney",
    clueId: "T-18",
    acceptedRpIds: ["R-13", "R-14"],
    acceptedMechIds: ["M-12", "M-05"],
    explanationTh: "ใช้ ⁹⁹ᵐTc-MAG3 ขับออกทาง Tubular Secretion หรือ ⁹⁹ᵐTc-DTPA ขับทาง Glomerular Filtration ร่วมกับการให้ยาขับปัสสาวะ Lasix",
    body: ["Diuretic Renogram ประเมินทางออกของไต"],
    illustration: "kidney",
    tags: ["kidney", "obstruction", "clinical"]
  },
  {
    id: "C-C10",
    type: "CASE",
    difficulty: "CLINICAL",
    points: 4,
    titleTh: "ความดันโลหิตสูงรุนแรง สงสัย Pheochromocytoma",
    titleEn: "Suspected Pheochromocytoma",
    promptTh: "ผู้ป่วยมีความดันโลหิตสูงวิกฤต หัวใจเต้นเร็ว เหงื่อออกมาก สงสัยเนื้องอกต่อมหมวกไต Pheochromocytoma",
    organHint: "adrenal",
    clueId: "T-20",
    acceptedRpIds: ["R-24"],
    acceptedMechIds: ["M-01"],
    explanationTh: "¹²³I-MIBG มีโครงสร้างเสมือน Norepinephrine ถูกลำเลียงเข้าสู่เซลล์ต่อมหมวกไตผ่าน Norepinephrine Transporter (Active Transport)",
    body: ["ตรวจเนื้องอกต่อมหมวกไตส่วนเมดัลลา"],
    illustration: "cell",
    tags: ["pheochromocytoma", "adrenal", "clinical"]
  }
];

export function validateCaseClues(
  cases: CaseCard[] = CASE_DECK,
  availableClueIds?: string[]
): { valid: boolean; missingClueCaseIds: string[] } {
  const allowed = availableClueIds ? new Set(availableClueIds) : null;
  const missing = cases
    .filter(c => !c.clueId || (allowed && !allowed.has(c.clueId)))
    .map(c => c.id);

  return {
    valid: missing.length === 0,
    missingClueCaseIds: missing
  };
}
