import { RadiopharmaceuticalCard } from "../types";

export const RADIOPHARMACEUTICAL_DECK: RadiopharmaceuticalCard[] = [
  {
    id: "R-01",
    type: "RP",
    titleTh: "เมแทบอลิซึมของกลูโคสในเซลล์",
    titleEn: "¹⁸F-FDG",
    subtitle: "Fluorodeoxyglucose",
    nuclide: "¹⁸F",
    modality: "PET",
    target: "Cell (metabolic activity)",
    transporter: "GLUT",
    mechanismId: "M-02",
    altMechanismIds: [],
    application: "Tumor imaging (whole body PET/CT), Myocardial viability, Brain metabolism",
    body: ["ติดฉลากกับฟลูออรีน-18", "สะสมในเซลล์ที่มีเมแทบอลิซึมสูง"],
    illustration: "cell",
    tags: ["pet", "tumor", "metabolism", "brain"]
  },
  {
    id: "R-02",
    type: "RP",
    titleTh: "การจับสารไอโอไดด์ของเซลล์ไทรอยด์",
    titleEn: "¹²³I-NaI",
    subtitle: "Sodium Iodide-123",
    nuclide: "¹²³I",
    modality: "SPECT",
    target: "Thyroid follicular cells",
    transporter: "Na⁺/I⁻ symporter (NIS)",
    mechanismId: "M-01",
    altMechanismIds: [],
    application: "Thyroid scintigraphy & uptake, Thyroid nodule evaluation",
    body: ["พลังงานแกมมา 159 keV เหมาะสมกับ Gamma Camera", "เข้าสู่เซลล์ด้วย Active Transport"],
    illustration: "thyroid",
    tags: ["thyroid", "spect", "nis"]
  },
  {
    id: "R-03",
    type: "RP",
    titleTh: "การดึงดูดไอออนประจุลบผ่าน NIS",
    titleEn: "⁹⁹ᵐTc-pertechnetate",
    subtitle: "Technetium-99m Sodium Pertechnetate",
    nuclide: "⁹⁹ᵐTc",
    modality: "SPECT",
    target: "Thyroid, Salivary glands, Gastric mucosa (Meckel's)",
    transporter: "Na⁺/I⁻ symporter (NIS)",
    mechanismId: "M-01",
    altMechanismIds: [],
    application: "Thyroid scan, Salivary scintigraphy, Meckel's diverticulum scan",
    body: ["ไอออน TcO4⁻ มีประจุและขนาดใกล้เคียงไอโอไดด์", "ถูกจับผ่าน NIS แต่ไม่เกิด organification"],
    illustration: "thyroid",
    tags: ["thyroid", "meckel", "nis"]
  },
  {
    id: "R-04",
    type: "RP",
    titleTh: "ไอโอดีนสำหรับการรักษาและการตรวจ",
    titleEn: "¹³¹I-NaI",
    subtitle: "Sodium Iodide-131",
    nuclide: "¹³¹I",
    modality: "SPECT",
    target: "Thyroid tissue & Thyroid cancer metastases",
    transporter: "Na⁺/I⁻ symporter (NIS)",
    mechanismId: "M-01",
    altMechanismIds: [],
    application: "Thyroid cancer post-op ablation, Hyperthyroidism therapy, Whole body scan",
    body: ["ปล่อยรังสีบีตาสำหรับรักษา และแกมมา 364 keV สำหรับตรวจ", "Active Transport ผ่าน NIS"],
    illustration: "thyroid",
    tags: ["thyroid", "therapy", "cancer"]
  },
  {
    id: "R-05",
    type: "RP",
    titleTh: "การดูดซับทางเคมีบนผลึกกระดูก",
    titleEn: "⁹⁹ᵐTc-MDP",
    subtitle: "Methylene Diphosphonate",
    nuclide: "⁹⁹ᵐTc",
    modality: "SPECT",
    target: "Bone (hydroxyapatite crystals)",
    mechanismId: "M-06",
    altMechanismIds: [],
    application: "Bone scan, Bone metastases detection, Osteomyelitis, Stress fracture",
    body: ["เกาะบนผลึกไฮดรอกซีอะพาไทต์ด้วย Chemisorption", "สะสมแปรผันตามการสร้างกระดูกและเลือดไปเลี้ยง"],
    illustration: "bone",
    tags: ["bone", "metastases", "fracture"]
  },
  {
    id: "R-06",
    type: "RP",
    titleTh: "การดูดซับทางเคมีบนผลึกกระดูกชนิด HDP",
    titleEn: "⁹⁹ᵐTc-HDP",
    subtitle: "Hydroxymethylene Diphosphonate",
    nuclide: "⁹⁹ᵐTc",
    modality: "SPECT",
    target: "Bone (hydroxyapatite crystals)",
    mechanismId: "M-06",
    altMechanismIds: [],
    application: "Bone scan, Bone remodeling evaluation",
    body: ["มี clearance ออกจากเลือดได้เร็วขึ้น", "เกาะกับผลึกกระดูกด้วย Chemisorption"],
    illustration: "bone",
    tags: ["bone", "spect"]
  },
  {
    id: "R-07",
    type: "RP",
    titleTh: "การอุดกั้นหลอดเลือดฝอยในปอด",
    titleEn: "⁹⁹ᵐTc-MAA",
    subtitle: "Macroaggregated Albumin",
    nuclide: "⁹⁹ᵐTc",
    modality: "SPECT",
    target: "Lung (pulmonary capillary bed)",
    mechanismId: "M-03",
    altMechanismIds: [],
    application: "Lung perfusion scan (Pulmonary Embolism diagnosis), Right-to-left shunt",
    body: ["อนุภาคโปรตีนขนาด 10–50 μm", "เกิด Capillary blockade ชั่วคราวในปอด"],
    illustration: "lung",
    tags: ["lung", "pe", "perfusion"]
  },
  {
    id: "R-08",
    type: "RP",
    titleTh: "การกระจายตัวในถุงลมปอด",
    titleEn: "⁹⁹ᵐTc-DTPA aerosol",
    subtitle: "Technetium-99m DTPA Aerosol",
    nuclide: "⁹⁹ᵐTc",
    modality: "SPECT",
    target: "Bronchioles and Alveolar space",
    mechanismId: "M-10",
    altMechanismIds: ["M-05"],
    application: "Lung ventilation scan (คู่กับ Perfusion scan ในการตรวจ PE)",
    body: ["พ่นเป็นละอองฝอยขนาดเล็กกว่า 2 μm สูดเข้าปอด", "Compartmental Localization ในถุงลม"],
    illustration: "lung",
    tags: ["lung", "ventilation", "pe"]
  },
  {
    id: "R-09",
    type: "RP",
    titleTh: "การกลืนกินโดยระบบ RES ของตับและม้าม",
    titleEn: "⁹⁹ᵐTc-sulfur colloid",
    subtitle: "Technetium-99m Sulfur Colloid",
    nuclide: "⁹⁹ᵐTc",
    modality: "SPECT",
    target: "Liver, Spleen, Bone marrow (Reticuloendothelial system)",
    mechanismId: "M-04",
    altMechanismIds: [],
    application: "Liver/spleen scan, Sentinel lymph node biopsy, Gastric emptying",
    body: ["อนุภาคคอลลอยด์ขนาด 0.1–1.0 μm", "ถูกเซลล์ Kupffer ดักจับด้วย Phagocytosis"],
    illustration: "liver_spleen",
    tags: ["liver", "spleen", "res", "sentinel"]
  },
  {
    id: "R-10",
    type: "RP",
    titleTh: "การขับผ่านเซลล์ตับและระบบน้ำดี",
    titleEn: "⁹⁹ᵐTc-mebrofenin",
    subtitle: "HIDA (Hepatobiliary Iminodiacetic Acid)",
    nuclide: "⁹⁹ᵐTc",
    modality: "SPECT",
    target: "Hepatocytes & Biliary tract",
    transporter: "OATP / MRP2",
    mechanismId: "M-01",
    altMechanismIds: ["M-12"],
    application: "HIDA scan, Acute cholecystitis, Biliary atresia, Bile leak",
    body: ["เซลล์ตับจับสารผ่าน Active transport แล้วขับลงถุงน้ำดี", "ประเมินการทำงานของถุงน้ำดีและท่อน้ำดี"],
    illustration: "liver_spleen",
    tags: ["hida", "liver", "gallbladder"]
  },
  {
    id: "R-11",
    type: "RP",
    titleTh: "การแลกเปลี่ยนไอออนบนผลึกกระดูกด้วย PET",
    titleEn: "¹⁸F-NaF",
    subtitle: "Sodium Fluoride-18",
    nuclide: "¹⁸F",
    modality: "PET",
    target: "Bone (hydroxyapatite crystal surface)",
    mechanismId: "M-06",
    altMechanismIds: ["M-11"],
    application: "PET Bone scan, High-resolution bone metastases detection",
    body: ["ฟลูออไรด์ไอออนแลกเปลี่ยนกับ OH⁻ ในผลึกกระดูก", "ให้ภาพ PET คมชัดสูงกว่า SPECT MDP ถึง 2 เท่า"],
    illustration: "bone",
    tags: ["bone", "pet", "fluoride"]
  },
  {
    id: "R-12",
    type: "RP",
    titleTh: "การจับในเซลล์เนื้อเยื่อไตส่วนนอก",
    titleEn: "⁹⁹ᵐTc-DMSA",
    subtitle: "Dimercaptosuccinic Acid",
    nuclide: "⁹⁹ᵐTc",
    modality: "SPECT",
    target: "Renal cortex (Proximal convoluted tubules)",
    mechanismId: "M-06",
    altMechanismIds: ["M-01"],
    application: "Renal cortical scintigraphy, Renal scarring, Acute pyelonephritis",
    body: ["เกาะติดกับเซลล์ท่อไตส่วนต้นแน่นหนา", "ประเมินแผลเป็นในเนื้อไต (Renal scar)"],
    illustration: "kidney",
    tags: ["kidney", "cortex", "scar"]
  },
  {
    id: "R-13",
    type: "RP",
    titleTh: "การหลั่งผ่านท่อไตเพื่อประเมินการทำงานของไต",
    titleEn: "⁹⁹ᵐTc-MAG3",
    subtitle: "Mercaptoacetyltriglycine",
    nuclide: "⁹⁹ᵐTc",
    modality: "SPECT",
    target: "Renal tubular cells (Tubular secretion)",
    mechanismId: "M-12",
    altMechanismIds: [],
    application: "Renogram (Diuretic renography), Ureteral obstruction, Renal transplant",
    body: ["ขับออกทาง Tubular secretion มากกว่า 95%", "เหมาะสำหรับผู้ป่วยที่มีภาวะไตบกพร่อง"],
    illustration: "kidney",
    tags: ["kidney", "renogram", "obstruction"]
  },
  {
    id: "R-14",
    type: "RP",
    titleTh: "การกรองผ่านโกลเมอรูลัสของไต",
    titleEn: "⁹⁹ᵐTc-DTPA IV",
    subtitle: "Diethylenetriaminepentaacetic Acid",
    nuclide: "⁹⁹ᵐTc",
    modality: "SPECT",
    target: "Glomerular filtration (GFR)",
    mechanismId: "M-05",
    altMechanismIds: [],
    application: "Glomerular Filtration Rate (GFR) measurement, Renal dynamic flow",
    body: ["ถูกกรองผ่านโกลเมอรูลัสอย่างเดียวโดยไม่มีการดูดกลับ", "กลไก Simple diffusion ตามแรงดันการกรอง"],
    illustration: "diffusion",
    tags: ["gfr", "kidney", "filtration"]
  },
  {
    id: "R-15",
    type: "RP",
    titleTh: "การจับกับตัวรับโซมาโตสแตติน",
    titleEn: "¹¹¹In-pentetreotide",
    subtitle: "Octreoscan (Somatostatin analog)",
    nuclide: "¹¹¹In",
    modality: "SPECT",
    target: "Somatostatin receptors (SSTR2, SSTR5)",
    transporter: "SSTR",
    mechanismId: "M-07",
    altMechanismIds: [],
    application: "Neuroendocrine tumor (NET) imaging, Carcinoid, Pheochromocytoma",
    body: ["แอนะล็อกของฮอร์โมน Somatostatin", "Receptor binding จับกับ SSTR บนผิวเซลล์เนื้องอก"],
    illustration: "receptor",
    tags: ["net", "tumor", "octreoscan"]
  },
  {
    id: "R-16",
    type: "RP",
    titleTh: "การจับตัวรับโซมาโตสแตตินด้วยภาพ PET",
    titleEn: "⁶⁸Ga-DOTATATE",
    subtitle: "Gallium-68 DOTATATE",
    nuclide: "⁶⁸Ga",
    modality: "PET",
    target: "Somatostatin receptor subtype 2 (SSTR2)",
    transporter: "SSTR2",
    mechanismId: "M-07",
    altMechanismIds: [],
    application: "NET PET/CT, Selection of patients for PRRT therapy (¹⁷⁷Lu-DOTATATE)",
    body: ["มีความจำเพาะต่อ SSTR2 สูงมาก", "ให้ภาพ PET คมชัดกว่า Octreoscan หลายเท่า"],
    illustration: "receptor",
    tags: ["net", "pet", "dotatate"]
  },
  {
    id: "R-17",
    type: "RP",
    titleTh: "การแพร่และยึดจับในไมโทคอนเดรีย",
    titleEn: "⁹⁹ᵐTc-sestamibi",
    subtitle: "Methoxyisobutylisonitrile (MIBI)",
    nuclide: "⁹⁹ᵐTc",
    modality: "SPECT",
    target: "Myocardium & Hyperfunctioning Parathyroid gland",
    mechanismId: "M-05",
    altMechanismIds: ["M-01"],
    application: "Myocardial Perfusion Imaging (MPI), Parathyroid adenoma localization",
    body: ["โมเลกุลไลโปฟิลิกประจุบวก แพร่ผ่านเยื่อหุ้มเซลล์", "จับติดแน่นกับไมโทคอนเดรียที่มีศักย์ไฟฟ้าลบ"],
    illustration: "cell",
    tags: ["heart", "parathyroid", "mpi"]
  },
  {
    id: "R-18",
    type: "RP",
    titleTh: "การทำงานเสมือนโพแทสเซียมในกล้ามเนื้อหัวใจ",
    titleEn: "²⁰¹Tl-chloride",
    subtitle: "Thallous Chloride-201",
    nuclide: "²⁰¹Tl",
    modality: "SPECT",
    target: "Viable myocardium",
    transporter: "Na⁺/K⁺ ATPase pump",
    mechanismId: "M-01",
    altMechanismIds: [],
    application: "Myocardial viability assessment, Stress-redistribution heart scan",
    body: ["ทำหน้าที่เสมือนโพแทสเซียมแอนะล็อก (K⁺ analog)", "เข้าสู่เซลล์กล้ามเนื้อหัวใจผ่าน Na⁺/K⁺ ATPase"],
    illustration: "cell",
    tags: ["heart", "viability", "thallium"]
  },
  {
    id: "R-19",
    type: "RP",
    titleTh: "การแพร่ผ่าน Blood-Brain Barrier ชนิด HMPAO",
    titleEn: "⁹⁹ᵐTc-HMPAO",
    subtitle: "Hexamethylpropyleneamine oxime (Exametazime)",
    nuclide: "⁹⁹ᵐTc",
    modality: "SPECT",
    target: "Brain cerebral cortex & WBC labeling",
    mechanismId: "M-05",
    altMechanismIds: ["M-02"],
    application: "Brain perfusion SPECT (Dementia, Epilepsy), Brain death, WBC labeling",
    body: ["เป็นกลางและละลายในไขมันดี จึงผ่าน BBB ได้", "เปลี่ยนรูปเป็นสารมีประจุติดอยู่ในเซลล์สมอง"],
    illustration: "cell",
    tags: ["brain", "perfusion", "wbc"]
  },
  {
    id: "R-20",
    type: "RP",
    titleTh: "การแพร่ผ่าน Blood-Brain Barrier ชนิด ECD",
    titleEn: "⁹⁹ᵐTc-ECD",
    subtitle: "Ethyl Cysteinate Dimer (Bicisate)",
    nuclide: "⁹⁹ᵐTc",
    modality: "SPECT",
    target: "Brain cerebral cortex",
    mechanismId: "M-05",
    altMechanismIds: ["M-02"],
    application: "Brain perfusion SPECT, Cerebrovascular disease evaluation",
    body: ["ผ่าน BBB ได้เร็ว และถูกเอนไซม์ Esterase ตัดเปลี่ยนรูป", "ขับออกจากเนื้อเยื่ออื่นได้เร็วกว่า HMPAO"],
    illustration: "cell",
    tags: ["brain", "perfusion", "stroke"]
  },
  {
    id: "R-21",
    type: "RP",
    titleTh: "การเคลื่อนที่ของเม็ดเลือดขาวติดฉลากรังสี",
    titleEn: "¹¹¹In-WBC",
    subtitle: "Indium-111 Labeled Leukocytes",
    nuclide: "¹¹¹In",
    modality: "SPECT",
    target: "Sites of acute infection & occult abscess",
    mechanismId: "M-08",
    altMechanismIds: [],
    application: "Occult infection detection, Osteomyelitis, Inflammatory bowel disease",
    body: ["ติดฉลากเม็ดเลือดขาวของผู้ป่วยเอง", "เคลื่อนที่ไปยังตำแหน่งติดเชื้อด้วยกลไก Cellular migration"],
    illustration: "migration",
    tags: ["infection", "wbc", "abscess"]
  },
  {
    id: "R-22",
    type: "RP",
    titleTh: "การกักจับเม็ดเลือดแดงที่ถูกทำลายด้วยความร้อน",
    titleEn: "Heat-damaged ⁹⁹ᵐTc-RBC",
    subtitle: "Denatured Red Blood Cells",
    nuclide: "⁹⁹ᵐTc",
    modality: "SPECT",
    target: "Splenic reticuloendothelial system",
    mechanismId: "M-09",
    altMechanismIds: [],
    application: "Detection of residual splenic tissue or Accessory spleen (Splenosis)",
    body: ["เม็ดเลือดแดงถูกอบความร้อน 49.5°C ให้เสียรูป", "ม้ามจะกรองและกักเก็บไว้ด้วย Cell sequestration"],
    illustration: "spleen",
    tags: ["spleen", "splenosis", "rbc"]
  },
  {
    id: "R-23",
    type: "RP",
    titleTh: "การกักกันในระบบหลอดเลือดเพื่อหาจุดเลือดออก",
    titleEn: "⁹⁹ᵐTc-RBC intact",
    subtitle: "In vitro/In vivo Labeled Red Blood Cells",
    nuclide: "⁹⁹ᵐTc",
    modality: "SPECT",
    target: "Intravascular blood pool",
    mechanismId: "M-10",
    altMechanismIds: [],
    application: "Gastrointestinal (GI) bleeding scan, Cardiac MUGA scan, Hepatic hemangioma",
    body: ["คงอยู่ในระบบไหลเวียนโลหิตเป็นเวลานาน", "เมื่อมีเลือดออกจะรั่วเข้าสู่ลำไส้ให้เห็นชัดเจน"],
    illustration: "compartment",
    tags: ["gi_bleed", "muga", "blood_pool"]
  },
  {
    id: "R-24",
    type: "RP",
    titleTh: "การดึงดูดเข้าสู่ระบบประสาทซิมพาเทติก",
    titleEn: "¹²³I-MIBG",
    subtitle: "Metaiodobenzylguanidine",
    nuclide: "¹²³I",
    modality: "SPECT",
    target: "Adrenal medulla & Sympathetic nervous system",
    transporter: "Norepinephrine transporter (NET)",
    mechanismId: "M-01",
    altMechanismIds: [],
    application: "Pheochromocytoma, Neuroblastoma, Cardiac sympathetic innervation",
    body: ["มีโครงสร้างคล้าย Norepinephrine", "เข้าสู่เซลล์ด้วย Active transport (Uptake-1)"],
    illustration: "cell",
    tags: ["pheochromocytoma", "adrenal", "neuroblastoma"]
  }
];
